name = "JLRye"
uuid = "149abf33-12ee-440d-ac90-48263f4b5770"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"

[targets]
test = ["Test", "ReferenceTests"]
